---
gems:
- jekyll-archives
- jekyll-sitemap
- jekyll-paginate
exclude:
- "/vendor/"
title: Centrarium
subtitle: A simple yet classy theme for your Jekyll website or blog
email: hsm63746244@gmail.com
name: Ben Centra
description: 'A simple yet classy theme for your Jekyll website or blog.

'
baseurl: ''
url: http://Seongmun-Hong.github.io
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: monokai-sublime
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: archive
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"
descriptions:
- cat: jekyll
  desc: Posts describing Jekyll setup techniques.
- cat: dummy
  desc: Just some placeholder posts, lorem ipsum and the rest.
social:
- name: GitHub
  icon: github
  username: bencentra
  url: https://github.com/Seongmun-Hong
  desc: Fork me on GitHub
  share: false
protocols:
  fb_image: "/assets/logo.png"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: "/assets/logo.png"
  os_repo: https://github.com/bencentra/centrarium.com
  os_rcs_type: git
  os_src: git@github.com:bencentra/centrarium.com.git
